name: Check for Malai Updates

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      actions: write

    steps:
      - name: Get latest Malai release
        id: malai-release
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/fastn-stack/kulfi/releases/latest | jq -r '.tag_name')
          echo "Latest Malai release: $LATEST_VERSION"
          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current version from Docker image
        id: current-version
        run: |
          # Use docker buildx imagetools to inspect the image
          IMAGE="${REGISTRY}/${IMAGE_NAME}:main"

          # Inspect image and extract the malai-version label
          CURRENT_VERSION=$(docker buildx imagetools inspect ${IMAGE} --raw | \
            jq -r '.config.Labels["org.opencontainers.image.malai-version"] // empty' 2>/dev/null || echo "")

          if [ -z "$CURRENT_VERSION" ]; then
            echo "Could not determine current version from image, will trigger build"
            echo "current_version=unknown" >> $GITHUB_OUTPUT
          else
            echo "Current version in image: $CURRENT_VERSION"
            echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Compare versions and trigger build
        if: steps.current-version.outputs.current_version != steps.malai-release.outputs.latest_version
        run: |
          echo "Version mismatch detected!"
          echo "Current: ${{ steps.current-version.outputs.current_version }}"
          echo "Latest: ${{ steps.malai-release.outputs.latest_version }}"
          echo "Triggering build workflow..."

      - name: Trigger Docker build
        if: steps.current-version.outputs.current_version != steps.malai-release.outputs.latest_version
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'docker-build.yml',
              ref: 'main',
              inputs: {
                malai_version: '${{ steps.malai-release.outputs.latest_version }}'
              }
            });

      - name: Summary
        run: |
          if [ "${{ steps.current-version.outputs.current_version }}" != "${{ steps.malai-release.outputs.latest_version }}" ]; then
            echo "## ✅ New Version Detected" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Triggered build for new Malai version:" >> $GITHUB_STEP_SUMMARY
            echo "- **Current:** ${{ steps.current-version.outputs.current_version }}" >> $GITHUB_STEP_SUMMARY
            echo "- **New:** ${{ steps.malai-release.outputs.latest_version }}" >> $GITHUB_STEP_SUMMARY
          else
            echo "## ℹ️ No Update Needed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Already using the latest version: ${{ steps.current-version.outputs.current_version }}" >> $GITHUB_STEP_SUMMARY
          fi
