name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      malai_version:
        description: 'Malai version tag (e.g., malai-0.2.9)'
        required: true
        type: string
  workflow_call:
    inputs:
      malai_version:
        description: 'Malai version tag (e.g., malai-0.2.9)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      malai_version: ${{ steps.version.outputs.malai_version }}
    steps:
      - name: Determine Malai version
        id: version
        run: |
          if [ -n "${{ inputs.malai_version }}" ]; then
            echo "malai_version=${{ inputs.malai_version }}" >> $GITHUB_OUTPUT
          else
            VERSION=$(curl -s https://api.github.com/repos/fastn-stack/kulfi/releases/latest | jq -r '.tag_name')
            echo "malai_version=$VERSION" >> $GITHUB_OUTPUT
          fi

  build-malai-binaries:
    needs: determine-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            arch: amd64
          - target: aarch64-unknown-linux-musl
            arch: arm64

    steps:
      - name: Checkout Kulfi repository
        uses: actions/checkout@v4
        with:
          repository: fastn-stack/kulfi
          ref: ${{ needs.determine-version.outputs.malai_version }}

      - name: Build Malai binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--locked --release --bin malai"

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: malai-${{ matrix.arch }}
          path: target/${{ matrix.target }}/release/malai
          retention-days: 1

  build-and-push:
    needs: [determine-version, build-malai-binaries]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download AMD64 binary
        uses: actions/download-artifact@v4
        with:
          name: malai-amd64
          path: ./binaries/amd64/

      - name: Download ARM64 binary
        uses: actions/download-artifact@v4
        with:
          name: malai-arm64
          path: ./binaries/arm64/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.malai-version=${{ needs.determine-version.outputs.malai_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
